### ISSUE TITLE
Request for source code

### ISSUE THREAD

**Issue by ARVINDEN** [turrogroup/rsvr#1]
Hi, I recently came across the preprint 'Genetic association analysis of 269 rare diseases reveals novel aetiologies'. I wish to implement the same in our dataset. However, I could not find the source code for rsvr database tool, where can I find the source code for the same. Thanks!!!

**Comment by eturro** [comment]
The repos is public now

**Comment by ARVINDEN** [comment]
Thanks Dr. Turro!!!
